Repository lblod/ember-rdfa-editor-standard-template-plugin, pull requests merged in 2022-09, with the labels that each got.

#24 chore(deps)!: bump editor to v0.63.1
  .drone.yml
  app/styles/app.scss
  package-lock.json
  package.json
  tests/dummy/app/styles/app.scss
Labels: breaking

#19 remove ember-cli-release and bump package.json file to version 2
  package-lock.json
  package.json
Labels: internal

#26 fix(selection-handler): handle cases with empty selection
  addon/components/template-provider.js
Labels: bug
